### ISSUE TITLE
Add-on launcher does not recognise Steam WebApp version of ED in profile

### ISSUE THREAD

**Issue by brammmers** [jimmyeao/Elite-Dangerous-Addon-Launcher-V2#17]
**Describe the bug**
I have a profile that launches ED:O via steam's web url: "steam://rungameid/359320", the addon launcher doesn't recognise this as ED.

**To Reproduce**
Add a profile and put an item in it to launch a web app using "steam://rungameid/359320", call it ED:O or "Elite Dangerous" - it doesn't matter the name.
**Expected behavior**
On launch the addon should open and wit for the "Launch" button to be pressed without prompting the user to add ED to the profile.

**Screenshots**
![image](https://github.com/jimmyeao/Elite-Dangerous-Addon-Launcher-V2/assets/3657420/98c545cf-56a3-4888-b671-05e882c9adb9)

![image](https://github.com/jimmyeao/Elite-Dangerous-Addon-Launcher-V2/assets/3657420/864dc3dc-8f45-4590-82f2-bd24bc8c28ac)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10 22H2, all patches applied from WinUpdate
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 115

**Additional context**
Using the webapp url is the only way I know to track game time in steam, running ED's exe directly doesn't do this and the new fdev launcher is a PITA to deal with anyway!

**Comment by brammmers** [comment]
This is on app version v1.1.2

**Comment by jimmyeao** [comment]
Thanks for the feedback, Ill try and get this fixed over the weekend

**Comment by jimmyeao** [comment]
Fixed in new release
