### ISSUE TITLE
Crash on Install

### ISSUE THREAD

**Issue by slider609** [jimmyeao/Elite-Dangerous-Addon-Launcher-V2#23]
**Describe the bug**

**To Reproduce**
1. Download and extract .zip file to Desktop
2. Run Setup.exe
3. See error

**Expected behavior**
Program to install

**Desktop (please complete the following information):**
 - Windows 11
 - Edge - 126.0.2592.102 (Official build) (64-bit)

install.log:

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package '.NET Desktop Runtime 7.0.5 (x64)', phase BuildList
Checking conditions before installer checks for command 'net7desktopruntime_x64\windowsdesktop-runtime-7.0.5-win-x64.exe'
Result of running operator 'ValueEqualTo' on property 'ProcessorArchitecture' and value 'Intel': false
Result of running operator 'ValueEqualTo' on property 'ProcessorArchitecture' and value 'Arm': false
Result of checking conditions before installer checks for command 'net7desktopruntime_x64\windowsdesktop-runtime-7.0.5-win-x64.exe' is: No action
Running external check with command 'C:\Users\[USER]\AppData\Local\Temp\VSD63DE.tmp\net7desktopruntime_x64\NetCoreCheck.exe' and parameters 'Microsoft.WindowsDesktop.App 7.0.5'
Process exited with code 0
Setting value '0 {int}' for property 'NetCoreCheck'
The following properties have been set for package '.NET Desktop Runtime 7.0.5 (x64)':
Property: [NetCoreCheck] = 0 {int}
Running checks for command 'net7desktopruntime_x64\windowsdesktop-runtime-7.0.5-win-x64.exe'
Result of running operator 'ValueEqualTo' on property 'ProcessorArchitecture' and value 'Intel': false
Result of running operator 'ValueEqualTo' on property 'ProcessorArchitecture' and value 'Arm': false
Result of running operator 'VersionLessThan' on property 'VersionNT' and value '6.1.0': false
Result of running operator 'ValueEqualTo' on property 'NetCoreCheck' and value '0': true
Result of checks for command 'net7desktopruntime_x64\windowsdesktop-runtime-7.0.5-win-x64.exe' is 'Bypass'
'.NET Desktop Runtime 7.0.5 (x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697210'
Error: An error occurred trying to download 'https://thfhaappstore.blob.core.windows.net/edlaunch/Elite%20Dangerous%20Addon%20Launcer%20V2.application'.

**Comment by jimmyeao** [comment]
Can you check this registry setting please to make sure you haven't turned off the caching of SSL pages?


[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
"DisableCachingOfSSLPages"=dword:00000000

**Comment by jimmyeao** [comment]
Also re-uploaded the latest release - I notice there was a typo:
'https://thfhaappstore.blob.core.windows.net/edlaunch/Elite%20Dangerous%20Addon%20**Launcer**%20V2.application'.
Launcher was spelled as "launcer"

**Comment by slider609** [comment]
> Also re-uploaded the latest release - I notice there was a typo: 'https://thfhaappstore.blob.core.windows.net/edlaunch/Elite%20Dangerous%20Addon%20**Launcer**%20V2.application'. Launcher was spelled as "launcer"

Can't download the latest version, virus detected by browsers.

**Comment by slider609** [comment]
> Can you check this registry setting please to make sure you haven't turned off the caching of SSL pages?
> 
> [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings] "DisableCachingOfSSLPages"=dword:00000000
> 
> Also make sure if you have any adblockers (pihole etc) it's not blocking https://*.blob.core.windows.net/

Not blocking and registry key was good.

**Comment by jimmyeao** [comment]
There is no virus, you can scan it with Windows Defender to check - likely flagged because it's not downloaded much smartscreen in windows always flags non-signed files it doesn't see much. 
Malware Bytes and MaxSecure incorrectly flag it, but all others are ok :([https://www.virustotal.com/gui/file/a0b6695e853cf3a587c56dc8c7d09a119f53a13908da654a4f1688d06e864464/detection](https://www.virustotal.com/gui/file/a0b6695e853cf3a587c56dc8c7d09a119f53a13908da654a4f1688d06e864464/detection ))
Here you can see from the behaviour tab what files are created etc if you want extra reassurance.

**Comment by jimmyeao** [comment]
Have updated some of the libraries (Material Design Themes) and re-uploaded

**Comment by jimmyeao** [comment]
New Virus Total Report [https://www.virustotal.com/gui/file/ab8f5e73f06e40cff46ef011f3f974dd0402a689f7b5170f4d1db7471e341d95/detection](https://www.virustotal.com/gui/file/ab8f5e73f06e40cff46ef011f3f974dd0402a689f7b5170f4d1db7471e341d95/detection)

**Comment by slider609** [comment]
Downloaded and install. Thank you.
