### ISSUE TITLE
App crashes when trying to Add Profile

### ISSUE THREAD

**Issue by slider609** [jimmyeao/Elite-Dangerous-Addon-Launcher-V2#25]
**Describe the bug**
After opening the app I click on Add Profile, the app then crashes

**To Reproduce**
1. Start Application
2. Click on Add Profile
4. App crashes without a message

**Expected behavior**
Ability to add a new profile

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Edge - 126.0.2592.102 (Official build) (64-bit)

**Additional context**
No error log created (that I could find).

**Comment by jimmyeao** [comment]
Found the bug, new version incoming shortly, thanks for highlighting this, seems to only effect "new" installs

**Comment by jimmyeao** [comment]
New release pushed, app should auto update on next run, let me know how you get on.

**Comment by slider609** [comment]
Looks like it's working fine.  I'm enjoying hitting one button to fire up four programs. I'll be creating a second profile for less common activities.

Thank you.
