### ISSUE TITLE
"/profile" and perhaps "/autolaunch" don't work

### ISSUE THREAD

**Issue by Thiesi** [jimmyeao/Elite-Dangerous-Addon-Launcher-V2#28]
**Describe the bug**
Adding the "/profile" and perhaps "/autolaunch" options to a shortcut to have the program load a profile and launch it without user input seems to do nothing.

**To Reproduce**
1. Download release 1.1.6.11.
2. Run installer/executable once to get all dependencies pulled in.
3. Create shortcut to installer/executable.
4. Add "/profile" and "/autolaunch" options to Target as per README.
5. Start program via shortcut.
6. Program starts normally as if said options were not present.

**Expected behavior**
As per README, "/profile" should select a profile, and "/autolaunch" should launch it.

**Screenshots**

![image](https://github.com/user-attachments/assets/5b717581-6d18-443d-a68d-b6b321259923)

![image](https://github.com/user-attachments/assets/897359c9-018f-436a-a7ef-41010bf05183)

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2 (Build 26100.1457)
 
**Additional context**
It might be "/autolaunch" is actually working but just not doing anything because "/profile" is not working to begin with, but for obvious reasons I can't test that. For reference, I'm also attaching an export of my current config.
[EDALv2.json](https://github.com/user-attachments/files/16649083/EDALv2.json)

**Comment by Thiesi** [comment]
Oh, I pulled the version info above from the config and the directory name in my profile, but it seems the actual version number is v1.1.6.10, so there seems to be a mismatch between the executable and the path.

**Comment by jimmyeao** [comment]
Thanks, Ill take a look this week and get it fixed :)

**Comment by jimmyeao** [comment]
You are running the setup.exe with switches, you need to find the main exe, mine is
C:\Users\jimmy\AppData\Local\Apps\2.0\RYGD7GYZ.Y3R\NXO211D8.QTR\elit...exe_0000000000000000_0001.0001_none_22ebf1efb (No idea why it is named that way!)
Search for "Elite Dangerous Addon Launcher V2.exe" and create the shortcut to that
