### ISSUE TITLE
"Rename Profile" crashes the program

### ISSUE THREAD

**Issue by Thiesi** [jimmyeao/Elite-Dangerous-Addon-Launcher-V2#29]
**Describe the bug**
If you select the "Rename Profile" command from the drop-down list, the program crashes.

**To Reproduce**
1. Download installer/executable for release 1.1.6.10.
2. Run installer/executable.
3. Add a new profile.
4. Restart the program.
5. Select "Rename Profile" from the drop-down list.

**Expected behavior**
I expected to be able to rename my profile.

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2 (Build 26100.1457)

**Additional context**
The program doesn't crash right away but only after around three to four seconds. Maybe it's trying to access a file in the background?

**Comment by jimmyeao** [comment]
Thanks, I'll try and reproduce and will push a fix once done

**Comment by MaverickMartyn** [comment]
This is also happening for me. It also applies to the "Duplicate Profile" button, so assume it has something to do with accessing the current profile. Maybe a null reference?

**Comment by jimmyeao** [comment]
Find the issue, will be pushing a new version shortly

**Comment by jimmyeao** [comment]
Fixed and pushed, re launch app to update
